### ISSUE TITLE
GDExtension issues tracker

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#442]
This tracks issues with GDExtension, as work is ongoing to port this module to it, and there are too many to be listed there. These issues are tracked because they currently prevent the module from working properly and reliably. Once enough of them are solved to allow production use, this tracker will be closed.

GDExtension/GodotCpp
-------------------------

### Missing features (or documentation needed)

- [ ] **C# support**: classes defined by extensions seem to not be accessible natively with C#. Same state as in GDNative, where you have to use slow `Call`, `Get` and `Set` with function names as string and no strong typing at all. So far only a module can expose an API. This is important as many users want to use C#, which is good candidate for heavier operations in games with voxel terrains.
- [x] **No separation of editor and release libraries**: just like the editor comes in two versions (editor and export templates), libraries must be able to do this too. However I don't recall GDNative having that feature. This may need a second check in GDExtension.
- [x] **Pointer access to typed arrays**: this was possible in GDNative, but got lost during the rewrite of GDExtension.
- [ ] **Singleton support**: because GDNative were considered scripts there was no other way to make singletons than to make the user create an autoload. This is not convenient. C++ modules can create singletons, and I think GDExtension now can, but there is an issue to solve about their cleanup on exit.
- [ ] **Method typing checks**: this seemed to not work in GDNative. Calling a GDNative function from GDScript did not seem to check arguments types, or argument count. They were casted silently for the better or for the worse. This may need a second check in GDExtension because I haven't tried it yet.
- [ ] **WebAssembly support**: this is relatively low priority but as far as I remember, there doesnt seem to be an easy documented way to make web libraries.
- [ ] **Documentation support**: the classes appear in the editor documentation pages but they don't have descriptions. That feature should be planned but appears to not be implemented yet.
- [ ] https://github.com/godotengine/godot/pull/65592: **Missing plugin registration**: there is no way to add multiple `EditorPlugins` through GDExtensions. The only way  is to use a `plugin.cfg` pointing to a script which then calls into the extension. Besides, `plugin.cfg` can register only one plugin, while this module contains more than one.
- [ ] https://github.com/godotengine/godot-cpp/issues/863: In GDScript, you can set custom icons to custom types either as a second argument to `class_name`, or by using `add_custom_type` from an editor plugin. This seems to be missing from GDExtension.

### Runtime issues

- [ ] **Cannot call Godot methods from constructors**: it crashes. This was also a problem in GDNative but was solved by defining a secondary constructor named `_init()`, which is called after the `owner` pointer is set. This was lost during the rewrite for GDExtensions so the problem is back.
- [ ] https://github.com/godotengine/godot-cpp/issues/624: when classes need to run in editor, there is a loading order bug which prevents libraries from working the first time after being added to the project. The editor needs to be closed and reopened again. This is a bad experience for plugin users.
- [ ] https://github.com/godotengine/godot-cpp/issues/615: GDExtension is advertised to allow scripts to extend from custom classes, but this doesn't seem to work yet. This module has a few APIs requiring this. Might be related to the classes not being recognized on the first load.
- [x] https://github.com/godotengine/godot-cpp/issues/614: class properties are not shown in inspector.  Might be related to the classes not being recognized on the first load.
- [ ] https://github.com/godotengine/godot-cpp/issues/610: GDExtension introduced the use of `virtual` C++ methods, which were not present in GDNative before. But this also broke casting object types, and needs to be solved.
- [ ] https://github.com/godotengine/godot-cpp/issues/652 Ref<T> doesn't work properly. Returning a Ref<T> causes a double-free crash. The cause and a possible fix were identified at the end of november 2021 with two PRs but no fix was approved yet.
- [ ] **Arrays and Dictionaries don't work well**: they need improvement, there are some missing APIs on them.

**Comment by SneaK1ng** [comment]
It seems to take a long time

**Comment by xkisu** [comment]
> EditorImportPlugin::_import is passing platform_variants and gen_files as const arrays. They are supposed to be modifiable, for the method to fill them in. It makes the method unusable and confusing. Workaround is to const_cast them, which is ugly.

I found this issue thread upon discovering the const issue myself in a plugin and thought I'd update you - I've raised it as an issue in the gotdot-cpp repository (https://github.com/godotengine/godot-cpp/issues/1471) and a [pull request draft](https://github.com/godotengine/godot/pull/92175) has been started to fix it!
